simple_oauth.oauth2_token.bundle.*:
  type: config_entity
  label: 'OAuth2 token type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked'

simple_oauth.oauth2_token_resource.*:
  type: config_entity
  label: 'Access Token Resource config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
          type: string
    uuid:
      type: string

simple_oauth.oauth2_client.*:
  type: config_entity
  label: 'Client config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    redirect_uri:
      type: uri
      label: 'Redirect URI'
    is_confidential:
      type: boolean
      label: 'Is confidential?'
    secret:
      type: string
      label: 'Secret key'
      description: 'Stores a hash of the secret ID using password_hash($secret, PASSWORD_BCRYPT).'

simple_oauth.oauth2_scope.*:
  type: config_entity
  label: 'Client config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    locked:
      type: boolean
      label: 'Locked'

simple_oauth.settings:
  type: mapping
  label: 'Token Auth Settings'
  mapping:
    expiration:
      type: integer
      label: 'Expiration Time'
      description: 'The default period in seconds while a token is valid'
