simple_oauth.oauth2_token.bundle.*:
  type: config_entity
  label: 'OAuth2 token type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked'

simple_oauth.settings:
  type: mapping
  label: 'Simple OAuth Settings'
  mapping:
    expiration:
      type: integer
      label: 'Expiration Time'
      description: 'The default period in seconds while a token is valid'
    use_implicit:
      type: integer
      label: 'Enable the implicit grant?'
      description: 'Only use the implicit grant if you understand the security implications of using it.'
    public_key:
      type: path
      label: 'Public Key'
      description: 'The path to the public file.'
    private_key:
      type: path
      label: 'Private Key'
      description: 'The path to the private file.'
