simple_oauth.oauth2_token.bundle.*:
  type: config_entity
  label: 'OAuth2 token type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked'

simple_oauth.oauth2_client.*:
  type: config_entity
  label: 'Client config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    redirectUri:
      type: uri
      label: 'Redirect URI'
    isConfidential:
      type: boolean
      label: 'Is confidential?'
    secret:
      type: string
      label: 'Secret key'
      description: 'Stores a hash of the secret ID.'
    roles:
      type: array
      label: 'Roles for the Client'
      description: 'These are the roles this application is entitiled to use.'
      items:
        type: string
        label: Role

simple_oauth.settings:
  type: mapping
  label: 'Simple OAuth Settings'
  mapping:
    expiration:
      type: integer
      label: 'Expiration Time'
      description: 'The default period in seconds while a token is valid'
    public_key:
      type: path
      label: 'Public Key'
      description: 'The path to the public file.'
    private_key:
      type: path
      label: 'Private Key'
      description: 'The path to the private file.'
