simple_oauth_3p.settings:
  type: mapping
  label: 'Simple OAuth 3rd Party Settings'
  mapping:
    use_implicit:
      type: integer
      label: 'Enable the implicit grant?'
      description: 'Only use the implicit grant if you understand the security implications of using it.'
